#include "ConstraintCreator.h"

#include "constraints/ServeMaster1555601736192Constraints.h"

#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

ConstraintCreator::ConstraintCreator() {}

ConstraintCreator::~ConstraintCreator() {}

shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
{
    switch (constraintConfId) {
    default:
        std::cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << std::endl;
        throw new std::exception();
        break;
    }
}

} // namespace alica
