#include "ServeMaster1555601736192.h"
/*PROTECTED REGION ID(eph1555601736192) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
// Check of PreCondition - (Name): 1558533725689, (ConditionString): Stop received , (Comment) :

/*
 * Available Vars:
 */
bool PreCondition1558533725689::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533725689) ENABLED START*/
    // TODO implement wm and check whether stop/start message was received
    return false;
    /*PROTECTED REGION END*/
}
/* generated comment
    Task: Serve  -> EntryPoint-ID: 1555601746711
*/
shared_ptr<UtilityFunction> UtilityFunction1555601736192::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1555601736192) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533620473, ConditionString: Start received, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): default, (PlanID): 1558533571134
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *
 * Vars:
 */
bool PreCondition1558533620473::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533492085) ENABLED START*/
    // TODO implement wm and check whether stop/start message was received
    return false;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533654035, ConditionString: Stop received, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): default, (PlanID): 1558533534828
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *
 * Vars:
 */
bool PreCondition1558533654035::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533494595) ENABLED START*/
    // TODO implement wm and check whether stop/start message was received
    return false;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1558533667052, ConditionString: Spawn successful, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): default, (PlanID): 1558533534828
 *
 * Tasks:
 *
 *   - Serve (1555601344076) (Entrypoint: 1555601746711)
 *
 * States:
 *
 *   - Stop (1555601748848)
 *   - Spawn (1558533460297)
 *   - Serve (1558533461982)
 *
 * Vars:
 */
bool PreCondition1558533667052::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1558533514929) ENABLED START*/
    // TODO implement wm and check whether stop/start message was received
    return false;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
