#include "constraints/ServeMaster1555601736192Constraints.h"
/*PROTECTED REGION ID(ch1555601736192) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
/*
 * Tasks:
 * - EP:1555601746711 : Serve (1555601344076)
 *
 * States:
 * - Stop (1555601748848)
 * - Spawn (1558533460297)
 * - Serve (1558533461982)
 *
 * Vars:
 */

/*
 * PreCondition - (Name): 1558533725689
 * (ConditionString): Stop received
 * Static Variables:
 * Domain Variables:
 *
 */
void Constraint1558533725689::getConstraint(std::shared_ptr<ProblemDescriptor> c, std::shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1558533725689) ENABLED START*/
    // Please describe your precondition constraint here
    /*PROTECTED REGION END*/
}

// State: Stop
// State: Spawn
// State: Serve
} // namespace alicaAutogenerated
