#include "constraints/ServeMaster1555601736192Constraints.h"
/*PROTECTED REGION ID(ch1555601736192) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
/*
 * Tasks:
 * - EP:1555601746711 : Serve (1555601344076)
 *
 * States:
 * - Default Name (1555601748848)
 *
 * Vars:
 */

// State: Default Name
} // namespace alicaAutogenerated
